### ISSUE TITLE
Extra leftover bracket at end of line causing deviceplane-agent startup failure

### ISSUE THREAD

**Issue by davidlu-ambient** [deviceplane/agent#1]
The following line has an extra `}` left at the end missed in the tidy commit. This causes the deviceplane-agent to pass in an invalid registration token.

https://github.com/deviceplane/agent/blob/9d36d136bef86ba55add9886deab793a4418e264/script/install.sh#L165

**Comment by sergerad** [comment]
Thanks very much @davidlu-ambient this has been fixed in [v1.18.2](https://github.com/deviceplane/agent/blob/v1.18.2/script/install.sh#L165)

**Comment by davidlu-ambient** [comment]
Thanks!
